import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  IonMenu,
  IonHeader,
  IonTitle,
  IonMenuToggle,
  IonItem,
  IonButton,
  IonContent,
  IonList,
  IonToolbar,
  IonMenuButton,
  IonButtons,
  IonLabel,
  IonCheckbox,
  IonFab,
  IonFabButton,
  IonIcon,
  IonInfiniteScroll,
  IonInfiniteScrollContent,
  IonReorder,
  IonReorderGroup,
} from '@ionic/angular/standalone';
import { FormsModule } from '@angular/forms';

@NgModule({
  imports: [
    CommonModule,
    IonMenu,
    IonButtons,
    IonButton,
    IonMenuButton,
    IonHeader,
    IonTitle,
    IonMenuToggle,
    IonItem,
    IonContent,
    IonList,
    IonToolbar,
    IonLabel,
    IonCheckbox,
    IonFab,
    IonFabButton,
    IonIcon,
    IonInfiniteScroll,
    IonInfiniteScrollContent,
    FormsModule,
    IonReorder,
    IonReorderGroup,
  ],
  exports: [
    CommonModule,
    IonMenu,
    IonButtons,
    IonButton,
    IonMenuButton,
    IonHeader,
    IonTitle,
    IonMenuToggle,
    IonItem,
    IonContent,
    IonList,
    IonToolbar,
    IonLabel,
    IonCheckbox,
    IonFab,
    IonFabButton,
    IonIcon,
    IonInfiniteScroll,
    IonInfiniteScrollContent,
    FormsModule,
    IonReorder,
    IonReorderGroup,
  ],
})
export class SharedModule {}
